apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: webapp
  labels:
    app: webapp
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3002
      targetPort: 3002
  selector:
    app: webapp
  type: ClusterIP