name: Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - release/dev
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      IMG_NAME: dantediy/gh-argocd-k8s
    steps:
      - name: Get code
        uses: actions/checkout@v3

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: ${{ env.IMG_NAME }}
      #     tags: |
      #       type=semver,pattern={{version}}
      #       type=semver,pattern={{major}}.{{minor}}
      #       type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Extract branch name & short sha
        id: branch_sha
        run: |
          echo "branch=$(echo ${GITHUB_REF#refs/heads/release/})" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "e_version=$(grep -m1 version server/core/constants/app-const.js | cut -d "'" -f2)" >> $GITHUB_OUTPUT
        
      # - name: Build and push docker images
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: |
      #       ${{ env.IMG_NAME }}:${{steps.branch_sha.outputs.branch}}-${{steps.branch_sha.outputs.sha_short}}
      #       ${{ env.IMG_NAME }}:${{steps.branch_sha.outputs.branch}}
      #       ${{ env.IMG_NAME }}:${{steps.branch_sha.outputs.e_version}}
      #       ${{ env.IMG_NAME }}:${{steps.branch_sha.outputs.branch}}-${{steps.branch_sha.outputs.e_version}}
      #     labels: ${{ steps.meta.outputs.labels }}

      - name: Checkout Config Repo
        uses: actions/checkout@v3
        with:
          repository: dantediy/gh-argocd-k8s-pri
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      - name: Replace version of deployment file
        run: |
          sed -i -e 's/${e_version}/${{steps.branch_sha.outputs.e_version}}/' ${GITHUB_WORKSPACE}/deployment/deployment.yml
          cat deployment/deployment.yml

      # - name: Push replaced deployment file to branch dev
      #   run: |
      #     git add deployment/*
